# Generated by Django 4.2.4 on 2023-09-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', '이메일'), ('google', '구글'), ('kakao', '카카오'), ('naver', '네이버')], default='email', max_length=50),
        ),
    ]
