# Generated by Django 4.2.4 on 2023-10-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_comment_content_announcement_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messages',
            new_name='message',
        ),
    ]
