#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# DJANGO_SETTINGS_MODULE이 있기 때문에 manage.py를 해도 prod버전이 실행됨
python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app